# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from pathlib import Path

sys.setrecursionlimit(5000)

import importlib.util as _importlib_util
_paddleocr_spec = _importlib_util.find_spec("paddleocr")
_paddleocr_dir = _paddleocr_spec.submodule_search_locations[0]
_cython_utility_dir = os.path.join(os.path.dirname(_importlib_util.find_spec("Cython").origin), "Utility")
_paddle_libs_dir = os.path.join(os.path.dirname(_importlib_util.find_spec("paddle").origin), "libs")

block_cipher = None

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("resources\\sounds", "resources\\sounds"),
        ("resources\\heartbeat3d", "resources\\heartbeat3d"),
        ("app-icons\\RedList.ico", "app-icons"),
        (_paddleocr_dir, "paddleocr"),
        (_paddle_libs_dir, "paddle\\libs"),
        (_cython_utility_dir, "Cython\\Utility"),
    ],
    hiddenimports=[
        "PyQt6.QtWebEngineWidgets",
        "PyQt6.QtWebEngineCore",
        "PyQt6.QtWebChannel",
        "src",
        "src.settings",
        "src.theme",
        "src.timer",
        "src.task_panel",
        "src.main_window",
        "src.settings_panel",
        "src.screenshot_legacy",
        "src.screenshot_translate",
        "src.llm_chat",
        "src.llm_chat.chat_panel",
        "src.llm_chat.chat_display",
        "src.llm_chat.chinese_menu",
        "src.llm_chat.conversation_list",
        "src.llm_chat.conversation_manager",
        "src.llm_chat.input_bar",
        "src.llm_chat.llm_service",
        "src.llm_chat.model_dialog",
        "src.llm_chat.prompt_expert_dialog",
        "src.ocr",
        "src.ocr.ocr_service",
        "src.overlay",
        "src.overlay.mask_overlay",
        "src.screenshot",
        "src.screenshot.region_selector",
        "src.screenshot.screenshot_tab",
        "src.screenshot.translate_panel",
        "src.screenshot.translation_thread",
        "src.recorder",
        "src.recorder.recorder_thread",
        "src.recorder.recording_indicator",
        "src.sticky_note",
        "src.sticky_note.manager",
        "src.sticky_note.panel",
        "src.sticky_note.window",
        "src.translation",
        "src.translation.translation_service",
        "src.utils",
        "src.utils.cache",
        "src.utils.color",
        "src.utils.debounce",
        "src.utils.geometry",
        "src.utils.logger",
        "src.utils.sound",
        "shapely",
        "pyclipper",
        "paddle",
        "cv2",
        "skimage",
        "skimage.morphology",
        "skimage.morphology._skeletonize",
        "PIL",
        "PIL.Image",
        "numpy",
        "mss",
        "tencentcloud",
        "tencentcloud.common",
        "tencentcloud.common.credential",
        "tencentcloud.common.profile.client_profile",
        "tencentcloud.common.profile.http_profile",
        "tencentcloud.tmt.v20180321.models",
        "tencentcloud.tmt.v20180321.tmt_client",
        "requests.adapters",
        "urllib3.util.retry",
        "docx",
        "openpyxl",
        "lmdb",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=["hook_paddleocr.py", "hook-runtime-paddle.py"],
    excludes=[
        "tkinter",
        "matplotlib",
        "torch",
        "tensorflow",
        "notebook",
        "jupyter",
        "IPython",
        "pandas",
        "pip",
        "nose",
        "sphinx",
        "PIL.ImageShow",
        "PIL.ImageQt",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="RedList",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="app-icons\\RedList.ico",
)

COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="RedList",
)
